/* Idiomas ES/EN/FR: diccionario y deteccion automatica. Para agregar o corregir textos edita SOLO este archivo. */
const I18={
es:{title:'Generador de Facturas Gratis Online | Crea Cuentas de Cobro y Recibos PDF',tab0:'Recibo de Venta',tab1:'Cuenta de Cobro',tab2:'Recibo de Caja',ct0:'Crea tu recibo de venta',ct1:'Crea tu cuenta de cobro',ct2:'Crea tu recibo de caja',
h1:'Generador Gratis de Facturas, Cuentas de Cobro y Recibos en PDF con Logo y QR',sub:'Crea facturas de venta, cuentas de cobro y recibos de caja para tiendas y freelancers. Agrega el logo de tu negocio con solo una foto, con código QR. <span>Gratis, sin registro: tus datos nunca salen de tu dispositivo.</span>',
opt_title:'Logo del negocio / Código QR',opt_hint:'(opcional)',opt_open:'Toca para abrir',opt_close:'Cerrar',lg_lbl:'Logo de tu negocio',qu_lbl:'Enlace para el QR (WhatsApp, Instagram o link de pago)',qp_lbl:'Propósito del QR',qp0:'Sin seleccionar (no mostrar QR)',qp1:'Recibir Pago',qp2:'Contactar por WhatsApp',qp3:'Seguir en Instagram',
pv:'Vista previa en vivo',tpl:'Plantilla',sty1:'Minimalista',sty2:'Ejecutiva',sty3:'Moderna',dl:'Descargar Factura en PDF',pdf_err:'No se pudo generar el PDF. Verifica tu conexión (la librería se carga por CDN) e inténtalo de nuevo.',copy:'© 2026 Generador de Facturas Gratis Online',f1:'Política de Privacidad',f2:'Términos de Servicio',f3:'Contacto',
invoice_title:'RECIBO DE VENTA',credit_note_title:'CUENTA DE COBRO',cash_receipt_title:'RECIBO DE CAJA',invoice_number:'N.º de consecutivo',date:'Fecha',due_date:'Fecha de vencimiento',emisor:'De (Emisor)',cliente:'Facturado a (Cliente)',description:'Descripción',quantity:'Cantidad',price:'Precio Unitario',total_item:'Importe',subtotal:'Subtotal',discount:'Descuento',tax:'IVA',total_due:'Total a pagar',payment_method:'Medio de pago',bank_details:'Datos de transferencia bancaria',signature_emisor:'Firma del emisor / Autorizado',signature_client:'Firma de recibido',
em_legend:'Datos del emisor',cl_legend:'Datos del cliente',l_name_co:'Nombre o empresa',doc_type:'Tipo de documento',doc_num:'Número de documento',ph_doc_num:'Solo si aplica',ph_doc_own:'Escribe el nombre del documento',back_list:'Volver a la lista',doc_word:'Documento',dt_none:'Sin documento',dt_cc:'Cédula de ciudadanía',dt_ce:'Cédula de extranjería',dt_pas:'Pasaporte',dt_lic:'Licencia de conducir',dt_rfc:'RFC (México)',dt_cuit:'CUIT / CUIL (Argentina)',dt_ruc:'RUC (Perú, Ecuador)',dt_nif:'NIF / CIF (España)',dt_tax:'Tax ID / EIN (EE. UU.)',dt_other:'Otro (escribir nombre)',
l_tel:'Teléfono',tel_s:'Tel',mail:'Correo',addr:'Dirección',cl_name:'Nombre del cliente',cl_ta:'Teléfono o dirección',cur_l:'Moneda',cur_other:'Otra (escribir manualmente)',cur_own:'Escribe tu moneda',ph_cur:'Ej: S/, Bs, CAD',
items_legend:'Artículos',add_row:'+ Añadir fila',del_row:'Eliminar fila',tax_lbl:'Impuesto / IVA % (opcional)',disc_lbl:'Descuento % (opcional)',ph_disc:'Ej. 10',notes_lbl:'Términos de garantía / notas (opcional)',ph_notes:'Ej. Garantía de 3 meses en fallas técnicas. No se realizan devoluciones de dinero.',notes_h:'Términos de garantía / notas',taxable_base:'Base imponible',
services_lbl:'Servicios prestados',ph_services:'Por concepto de: servicios profesionales de diseño UI/UX para sitio web - Fase 1',val_lbl:'Valor del trabajo',ph_due:'Ej. 15 de octubre de 2026 o 5 días hábiles',l_bank:'Banco',l_acct_type:'Tipo de cuenta',ph_acct_type:'Ahorros / Corriente',l_acct_no:'Número de cuenta',acct_no:'Número',
received_from:'Recibí de',l_sum:'La suma de',l_concept:'Concepto detallado del ingreso',ph_concept:'Ej. Pago total de la factura N.º 105 o abono inicial para desarrollo web',for_concept:'Por concepto de',pm0:'Efectivo',pm1:'Transferencia bancaria',pm2:'Tarjeta de crédito',pm3:'Tarjeta débito',pm4:'Plataforma digital',pm5:'Cheque',pm6:'Otro',
tl1:'Valor a cobrar',tl2:'Valor recibido',qt:'Escanea para pagar o contactar',sg_by:'Entregado por',sg_rec:'Recibido por'},
en:{title:'Free Online Invoice Generator | Create Invoices and Receipts in PDF',tab0:'Sales Invoice',tab1:'Fee Statement',tab2:'Cash Receipt',ct0:'Create your sales invoice',ct1:'Create your fee statement',ct2:'Create your cash receipt',
h1:'Free Invoice, Fee Statement and Receipt Generator in PDF with Logo and QR',sub:'Create sales invoices, fee statements and cash receipts for shops and freelancers. Add your business logo with just a photo, plus a QR code. <span>Free, no sign-up: your data never leaves your device.</span>',
opt_title:'Business logo / QR code',opt_hint:'(optional)',opt_open:'Tap to open',opt_close:'Close',lg_lbl:'Your business logo',qu_lbl:'QR link (WhatsApp, Instagram or payment link)',qp_lbl:'QR purpose',qp0:'Not selected (hide QR)',qp1:'Receive payment',qp2:'Contact on WhatsApp',qp3:'Follow on Instagram',
pv:'Live preview',tpl:'Template',sty1:'Minimalist',sty2:'Executive',sty3:'Modern',dl:'Download Invoice as PDF',pdf_err:'The PDF could not be generated. Check your connection (the library loads from a CDN) and try again.',copy:'© 2026 Free Online Invoice Generator',f1:'Privacy Policy',f2:'Terms of Service',f3:'Contact',
invoice_title:'SALES INVOICE',credit_note_title:'FEE STATEMENT',cash_receipt_title:'CASH RECEIPT',invoice_number:'Invoice No.',date:'Date',due_date:'Due Date',emisor:'From (Issuer)',cliente:'Bill To (Customer)',description:'Description',quantity:'Qty',price:'Unit Price',total_item:'Amount',subtotal:'Subtotal',discount:'Discount',tax:'Tax / VAT',total_due:'Total Due',payment_method:'Payment Method',bank_details:'Bank Transfer Information',signature_emisor:'Authorized Signature',signature_client:'Received By (Signature)',
em_legend:'Issuer details',cl_legend:'Customer details',l_name_co:'Name or company',doc_type:'Document type',doc_num:'Document number',ph_doc_num:'Only if applicable',ph_doc_own:'Type the document name',back_list:'Back to list',doc_word:'Document',dt_none:'No document',dt_cc:'National ID card',dt_ce:'Foreigner ID card',dt_pas:'Passport',dt_lic:"Driver's license",dt_rfc:'RFC (Mexico)',dt_cuit:'CUIT / CUIL (Argentina)',dt_ruc:'RUC (Peru, Ecuador)',dt_nif:'NIF / CIF (Spain)',dt_tax:'Tax ID / EIN (USA)',dt_other:'Other (type name)',
l_tel:'Phone',tel_s:'Tel',mail:'Email',addr:'Address',cl_name:'Customer name',cl_ta:'Phone or address',cur_l:'Currency',cur_other:'Other (type manually)',cur_own:'Type your currency',ph_cur:'E.g. S/, Bs, CAD',
items_legend:'Items',add_row:'+ Add row',del_row:'Delete row',tax_lbl:'Tax / VAT % (optional)',disc_lbl:'Discount % (optional)',ph_disc:'E.g. 10',notes_lbl:'Warranty terms / notes (optional)',ph_notes:'E.g. 3-month warranty on technical faults. No cash refunds.',notes_h:'Warranty terms / notes',taxable_base:'Taxable base',
services_lbl:'Services provided',ph_services:'For: professional UI/UX design services for website - Phase 1',val_lbl:'Fee amount',ph_due:'E.g. October 15, 2026 or 5 business days',l_bank:'Bank',l_acct_type:'Account type',ph_acct_type:'Savings / Checking',l_acct_no:'Account number',acct_no:'Number',
received_from:'Received from',l_sum:'The sum of',l_concept:'Detailed concept of the payment',ph_concept:'E.g. Full payment of invoice No. 105 or initial deposit for web development',for_concept:'For the concept of',pm0:'Cash',pm1:'Bank transfer',pm2:'Credit card',pm3:'Debit card',pm4:'Digital platform',pm5:'Check',pm6:'Other',
tl1:'Amount due',tl2:'Amount received',qt:'Scan to pay or get in touch',sg_by:'Delivered by',sg_rec:'Received by'},
fr:{title:'Générateur de factures gratuit en ligne | Factures et reçus en PDF',tab0:'Facture de vente',tab1:'Demande de paiement',tab2:'Reçu de caisse',ct0:'Créez votre facture de vente',ct1:'Créez votre demande de paiement',ct2:'Créez votre reçu de caisse',
h1:'Générateur gratuit de factures, demandes de paiement et reçus en PDF avec logo et QR',sub:"Créez des factures de vente, des demandes de paiement et des reçus de caisse pour commerces et freelances. Ajoutez le logo de votre entreprise avec une simple photo, avec un code QR. <span>Gratuit, sans inscription : vos données ne quittent jamais votre appareil.</span>",
opt_title:"Logo de l'entreprise / Code QR",opt_hint:'(facultatif)',opt_open:'Touchez pour ouvrir',opt_close:'Fermer',lg_lbl:'Logo de votre entreprise',qu_lbl:'Lien du QR (WhatsApp, Instagram ou lien de paiement)',qp_lbl:'Objectif du QR',qp0:'Non sélectionné (masquer le QR)',qp1:'Recevoir un paiement',qp2:'Contacter sur WhatsApp',qp3:'Suivre sur Instagram',
pv:'Aperçu en direct',tpl:'Modèle',sty1:'Minimaliste',sty2:'Exécutif',sty3:'Moderne',dl:'Télécharger la facture en PDF',pdf_err:"Impossible de générer le PDF. Vérifiez votre connexion (la bibliothèque se charge via CDN) et réessayez.",copy:'© 2026 Générateur de factures gratuit en ligne',f1:'Politique de confidentialité',f2:"Conditions d'utilisation",f3:'Contact',
invoice_title:'FACTURE DE VENTE',credit_note_title:'DEMANDE DE PAIEMENT',cash_receipt_title:'REÇU DE CAISSE',invoice_number:'Facture N°',date:'Date',due_date:"Date d'échéance",emisor:'De (Émetteur)',cliente:'Facturé à (Client)',description:'Description',quantity:'Qté',price:'Prix Unitaire',total_item:'Montant',subtotal:'Sous-total',discount:'Remise',tax:'TVA',total_due:'Total à payer',payment_method:'Mode de paiement',bank_details:'Informations de transfert bancaire',signature_emisor:'Signature autorisée',signature_client:'Signature de réception',
em_legend:"Données de l'émetteur",cl_legend:'Données du client',l_name_co:'Nom ou entreprise',doc_type:'Type de document',doc_num:'Numéro du document',ph_doc_num:'Seulement si applicable',ph_doc_own:'Saisissez le nom du document',back_list:'Retour à la liste',doc_word:'Document',dt_none:'Sans document',dt_cc:"Carte d'identité",dt_ce:"Carte d'identité étrangère",dt_pas:'Passeport',dt_lic:'Permis de conduire',dt_rfc:'RFC (Mexique)',dt_cuit:'CUIT / CUIL (Argentine)',dt_ruc:'RUC (Pérou, Équateur)',dt_nif:'NIF / CIF (Espagne)',dt_tax:'Tax ID / EIN (États-Unis)',dt_other:'Autre (saisir le nom)',
l_tel:'Téléphone',tel_s:'Tél',mail:'E-mail',addr:'Adresse',cl_name:'Nom du client',cl_ta:'Téléphone ou adresse',cur_l:'Devise',cur_other:'Autre (saisir manuellement)',cur_own:'Saisissez votre devise',ph_cur:'Ex. S/, Bs, CAD',
items_legend:'Articles',add_row:'+ Ajouter une ligne',del_row:'Supprimer la ligne',tax_lbl:'TVA / Taxe % (facultatif)',disc_lbl:'Remise % (facultatif)',ph_disc:'Ex. 10',notes_lbl:'Conditions de garantie / notes (facultatif)',ph_notes:"Ex. Garantie de 3 mois sur les pannes techniques. Aucun remboursement en espèces.",notes_h:'Conditions de garantie / notes',taxable_base:'Base imposable',
services_lbl:'Services rendus',ph_services:'Pour : services professionnels de design UI/UX pour site web - Phase 1',val_lbl:'Montant des travaux',ph_due:"Ex. 15 octobre 2026 ou 5 jours ouvrés",l_bank:'Banque',l_acct_type:'Type de compte',ph_acct_type:'Épargne / Courant',l_acct_no:'Numéro de compte',acct_no:'Numéro',
received_from:'Reçu de',l_sum:'La somme de',l_concept:'Motif détaillé du paiement',ph_concept:"Ex. Paiement total de la facture N° 105 ou acompte pour développement web",for_concept:'Pour le motif de',pm0:'Espèces',pm1:'Virement bancaire',pm2:'Carte de crédit',pm3:'Carte de débit',pm4:'Plateforme numérique',pm5:'Chèque',pm6:'Autre',
tl1:'Montant dû',tl2:'Montant reçu',qt:'Scannez pour payer ou contacter',sg_by:'Remis par',sg_rec:'Reçu par'}};
const LOC={es:'es-CO',en:'en-US',fr:'fr-FR'};
let lang='es';
try{lang=localStorage.getItem('lang')}catch(e){}
if(!I18[lang]){const n=String((navigator.languages&&navigator.languages[0])||navigator.language||navigator.userLanguage||'es').toLowerCase();lang=n.indexOf('en')==0?'en':n.indexOf('fr')==0?'fr':'es'}
const T=k=>(I18[lang]&&I18[lang][k]!=null)?I18[lang][k]:(I18.es[k]!=null?I18.es[k]:k);
